#
# Default configuration options for LeapKeyDaemon
#

# couch connection configuration
connection:
  protocol: "http"
  host: "localhost"
  port: 5984
  username: ~
  password: ~
  prefix: ""
  suffix: ""

# file to store the last processed user record in so we can resume after
# a restart:
seq_file: "/var/log/leap/key_daemon.seq"

# Configure log_file like this if you want to log to a file instead of syslog:
# log_file: "/var/leap/log/key_daemon.log"
log_level: debug

options:
  # URL of a keyserver that supports uploading keys at /pks/add
  keyserver: "http://pgp.mit.edu:11371"
